#! /bin/sh

bspc config top_padding         24
bspc config bottom_padding      50
bspc config border_width        5
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer   true

bspc monitor DVI-I-2 -d II IV
bspc monitor DVI-I-3 -d I III

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

